---
abstract: 'FastCGI handler for Plack using Net::FastCGI'
author:
  - 'Christian Hansen C<chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Handler-Net-FastCGI
no_index:
  directory:
    - inc
    - t
requires:
  Net::FastCGI: 12
  Plack: 0.9985
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chansen/p5-plack-handler-net-fastcgi
version: 0.01
